import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import ThemeToggle from "./theme-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen transition-colors bg-[var(--app-bg)] text-[var(--text)]`}
      > 
        {/* Set initial theme before hydration to avoid FOUC */}
        <Script id="init-theme" strategy="beforeInteractive">
          {`
            try {
              const stored = localStorage.getItem('theme');
              const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
              const theme = stored || (prefersDark ? 'dark' : 'light');
              document.documentElement.setAttribute('data-theme', theme);
            } catch (e) { /* no-op */ }
          `}
        </Script>

        {/* Mobile viewport */}
        <div className="md:hidden min-h-screen p-0 relative">
          <ThemeToggle />
          <div className="w-full">{children}</div>
        </div>

        {/* Desktop/Tablet notice */}
        <div className="hidden md:flex min-h-screen items-center justify-center p-8">
          <div className="max-w-md text-center space-y-3">
            <h1 className="text-2xl font-semibold">Studyflow is mobile-only</h1>
            <p className="text-gray-600">Please open this app on your phone or resize the window below 768px width.</p>
          </div>
        </div>
      </body>
    </html>
  );
}
